### PR TITLE
Initial commit of kinematic model and unit testing changes

### PR DESCRIPTION
**Pull request by msmcconnell**
This PR adds a basic kinematic vehicle model and updates the lib_vehicle_model library to support more complex behavior during integration. The changes include 

* Add a tracker ODESolver which allows users to arbitrarily track information between iterations and samples. This is used to track the t of the previous timestep for computing delta t on the fly. However, the tracker will also be used in future PRs for controller response simulation

* Created model_test_tools package which contains helpful functions and classes for unit testing of vehicle models based on rosbags. 

* Adds some rosbags to the repo for unit test execution

* Adds the passenger_car_kinematic_model package which implements the simplest possible kinematic bicycle model. 

The model 
image

Originally from 
http://www.cs.cmu.edu/~motionplanning/reading/PlanningforDynamicVeh-1.pdf

### CODE REVIEW

**Comment by aswath1** [comment]
kinematic vehicle model looks good.
 lib_vehicle_model with extended support is accurate and helps for complex task.

**Comment by msmcconnell** [comment]
@aswath1 Did you mean to close this?

**Review by aswath1 — DISMISSED** [review]
kinematic vehicle model looks good.
lib_vehicle_model with extended support is accurate and helps for complex task.

**Review by aswath1 — DISMISSED** [review]
CI build error corrected.

**Review by aswath1 — APPROVED** [review]
Code Coverage fix.

**Pull request merged**
